"""add cascade delete on customer_id table address

Revision ID: 377407cec94b
Revises: e52a304ce773
Create Date: 2024-07-08 12:38:16.569334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377407cec94b'
down_revision = 'e52a304ce773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint('address_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['customer_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('address_ibfk_1', 'customers', ['customer_id'], ['customer_id'])

    # ### end Alembic commands ###
